wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: apoorv1009 (apoorv10). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /fs/classhomes/fall2024/cmsc848k/c848k062/ObitoNet/wandb/run-20241213_210521-2jieo12z
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run absurd-eon-4
wandb: ‚≠êÔ∏è View project at https://wandb.ai/apoorv10/obitonet
wandb: üöÄ View run at https://wandb.ai/apoorv10/obitonet/runs/2jieo12z
Traceback (most recent call last):
  File "/fs/classhomes/fall2024/cmsc848k/c848k062/ObitoNet/main.py", line 90, in <module>
    main()
  File "/fs/classhomes/fall2024/cmsc848k/c848k062/ObitoNet/main.py", line 41, in main
    dist_utils.init_dist(args.launcher)
  File "/fs/classhomes/fall2024/cmsc848k/c848k062/ObitoNet/utils/dist_utils.py", line 13, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/fs/classhomes/fall2024/cmsc848k/c848k062/ObitoNet/utils/dist_utils.py", line 20, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/fs/classhomes/fall2024/cmsc848k/c848k062/miniconda3/envs/obito_env/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
[1;34mwandb[0m: üöÄ View run [33mabsurd-eon-4[0m at: [34mhttps://wandb.ai/apoorv10/obitonet/runs/2jieo12z[0m
[1;34mwandb[0m: Find logs at: [1;35mwandb/run-20241213_210521-2jieo12z/logs[0m
srun: error: tron46: task 0: Exited with exit code 1
ran successfully
